/** @jsxImportSource hono/jsx */

/**
 * <Picture> — the §8.2 image set as markup.
 *
 * AVIF with a WebP fallback and a JPEG floor, responsive widths, and a blur-up
 * placeholder inlined from the build manifest so there is something on screen
 * before the bytes land.
 *
 * If an image has not been generated yet, this renders a plain tone block
 * instead of a broken <img>. That case is real right now — the photographs are
 * generated by a script that needs Cloudflare credentials, and until someone
 * runs it the site has to look deliberate rather than broken.
 */

import manifest from '../../shared/imagery-manifest.json';
import { byId, objectKey, type ImageId } from '../../shared/imagery';

interface ManifestEntry {
  id: string;
  width: number;
  height: number;
  lqip: string;
  bytes: Record<string, number>;
}

const ENTRIES = manifest as Record<string, ManifestEntry>;

export function hasImage(id: ImageId): boolean {
  return Boolean(ENTRIES[id]);
}

function srcset(id: ImageId, widths: number[], format: 'avif' | 'webp' | 'jpeg'): string {
  return widths.map((w) => `/media/${objectKey(id, w, format)} ${w}w`).join(', ');
}

interface PictureProps {
  id: ImageId;
  /** Maps viewport to rendered width. Wrong sizes costs more than wrong format. */
  sizes: string;
  className?: string;
  /** The hero is the LCP element and must not be lazy. Everything else is. */
  priority?: boolean;
  style?: string;
}

export function Picture({ id, sizes, className, priority = false, style }: PictureProps) {
  const spec = byId(id);
  const entry = ENTRIES[id];

  if (!entry) {
    /*
     * No photograph yet. A tone in the palette reads as a design choice; a
     * broken image icon reads as an abandoned site. Warm rather than near-
     * black, because the hero sits under a dark scrim and two dark layers
     * together look like a rendering failure rather than a photograph that has
     * not arrived.
     */
    return (
      <div
        class={className}
        role="img"
        aria-label={spec.alt}
        style={`background:radial-gradient(120% 100% at 30% 15%,#4a4038 0%,#2b2621 55%,#1b1815 100%);aspect-ratio:${spec.width}/${spec.height};${style ?? ''}`}
      />
    );
  }

  return (
    <picture>
      <source type="image/avif" srcset={srcset(id, spec.widths, 'avif')} sizes={sizes} />
      <source type="image/webp" srcset={srcset(id, spec.widths, 'webp')} sizes={sizes} />
      <img
        src={`/media/${objectKey(id, spec.widths[0], 'jpeg')}`}
        srcset={srcset(id, spec.widths, 'jpeg')}
        sizes={sizes}
        alt={spec.alt}
        width={entry.width}
        height={entry.height}
        class={className}
        loading={priority ? 'eager' : 'lazy'}
        // fetchpriority on the LCP image is worth more than any byte we could
        // shave off it.
        fetchpriority={priority ? 'high' : 'auto'}
        decoding={priority ? 'sync' : 'async'}
        style={`background-image:url(${entry.lqip});background-size:cover;background-position:center;${style ?? ''}`}
      />
    </picture>
  );
}
